package application;

import vending_machine.*;
import javafx.fxml.FXML;

import java.util.ArrayList;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public class SampleController {
	@FXML
	private ImageView slot0;
	@FXML
	private ImageView slot1;
	@FXML
	private ImageView slot2;
	@FXML
	private ImageView slot3;
	@FXML
	private ImageView slot4;
	@FXML
	private ImageView slot5;
	@FXML
	private ImageView slot6;
	@FXML
	private ImageView slot7;
	@FXML
	private ImageView dispensed;
	@FXML
	private ImageView black;
	@FXML
	private Label amt0;
	@FXML
	private Label amt1;
	@FXML
	private Label amt2;
	@FXML
	private Label amt3;
	@FXML
	private Label amt4;
	@FXML
	private Label amt5;
	@FXML
	private Label amt6;
	@FXML
	private Label amt7;
	@FXML
	private Label amt01;
	@FXML
	private Label amt02;
	@FXML
	private Label amt03;
	@FXML
	private Label amt04;
	@FXML
	private Label amt05;
	@FXML
	private Label amt06;
	@FXML
	private Label amt07;
	@FXML
	private Label amt08;

	DataFile myData;
	ArrayList <String> myVending;
	ArrayList <Integer> mySelections;
	Vending myMachine;
	
	
	public void initialize() {
		myData = new DataFile("directory.txt", "input.txt");
		myVending = myData.loadDirectory();
	    mySelections = myData.loadSampleInput();
	    myMachine = new Vending(myVending);
	    
	    // System.out.println(myMachine);
	    
	    Integer st = myMachine.slots.get(0).size();
	    this.amt0.setText(st.toString());
	    
	    st = myMachine.slots.get(1).size();
	    this.amt1.setText(st.toString());
	    
	    st = myMachine.slots.get(2).size();
	    this.amt2.setText(st.toString());
	    
	    st = myMachine.slots.get(3).size();
	    this.amt3.setText(st.toString());
	    
	    st = myMachine.slots.get(4).size();
	    this.amt4.setText(st.toString());
	    
	    st = myMachine.slots.get(5).size();
	    this.amt5.setText(st.toString());
	    
	    st = myMachine.slots.get(6).size();
	    this.amt6.setText(st.toString());
	    
	    st = myMachine.slots.get(7).size();
	    this.amt7.setText(st.toString());
	    
	    slot0.setVisible(true);
	    slot1.setVisible(true);
	    slot2.setVisible(true);
	    slot3.setVisible(true);
	    slot4.setVisible(true);
	    slot5.setVisible(true);
	    slot6.setVisible(true);
	    slot7.setVisible(true);
	    
	}
	
	public void set_amts() {
	    Integer st = myMachine.slots.get(0).size();
	    this.amt0.setText(st.toString());
	    
	    st = myMachine.slots.get(1).size();
	    this.amt1.setText(st.toString());
	    
	    st = myMachine.slots.get(2).size();
	    this.amt2.setText(st.toString());
	    
	    st = myMachine.slots.get(3).size();
	    this.amt3.setText(st.toString());
	    
	    st = myMachine.slots.get(4).size();
	    this.amt4.setText(st.toString());
	    
	    st = myMachine.slots.get(5).size();
	    this.amt5.setText(st.toString());
	    
	    st = myMachine.slots.get(6).size();
	    this.amt6.setText(st.toString());
	    
	    st = myMachine.slots.get(7).size();
	    this.amt7.setText(st.toString());
	}
	
	public void set_vis() {
		if (myMachine.slots.get(0).size() == 0) {
			slot0.setVisible(false);
		}
		if (myMachine.slots.get(1).size() == 0) {
			slot1.setVisible(false);
		}
		if (myMachine.slots.get(2).size() == 0) {
			slot2.setVisible(false);
		}
		if (myMachine.slots.get(3).size() == 0) {
			slot3.setVisible(false);
		}
		if (myMachine.slots.get(4).size() == 0) {
			slot4.setVisible(false);
		}
		if (myMachine.slots.get(5).size() == 0) {
			slot5.setVisible(false);
		}
		if (myMachine.slots.get(6).size() == 0) {
			slot6.setVisible(false);
		}
		if (myMachine.slots.get(7).size() == 0) {
			slot7.setVisible(false);
		}
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void btn0Click(ActionEvent event) {
		// TODO Autogenerated
		
		if (!myMachine.findProduct(myMachine.directory.get(0)).isEmpty()) {
			dispensed.setImage(slot0.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(0);
		
		set_amts();
		

		
		set_vis();
    	
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn1Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(1)).isEmpty()) {
			dispensed.setImage(slot1.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(1);
		
		set_amts();
		
		
		set_vis();

	}
	// Event Listener on Button.onAction
	@FXML
	public void btn2Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(2)).isEmpty()) {
			dispensed.setImage(slot2.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(2);
	
		set_amts();
		
		
		set_vis();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn3Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(3)).isEmpty()) {
			dispensed.setImage(slot3.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(3);
		
		set_amts();
		
		set_vis();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn4Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(4)).isEmpty()) {
			dispensed.setImage(slot4.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(4);
		
		set_amts();
		
		set_vis();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn5Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(5)).isEmpty()) {
			dispensed.setImage(slot5.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(5);
		
		set_amts();
		
		set_vis();

	}
	// Event Listener on Button.onAction
	@FXML
	public void btn6Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(6)).isEmpty()) {
			dispensed.setImage(slot6.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(6);
		
		set_amts();
		
		set_vis();
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn7Click(ActionEvent event) {
		// TODO Autogenerated
		if (!myMachine.findProduct(myMachine.directory.get(7)).isEmpty()) {
			dispensed.setImage(slot7.getImage());
			dispensed.setVisible(true);
		}
		else {
			dispensed.setVisible(false);
		}
		
		myMachine.unloadItem(7);
		
		set_amts();
		
		set_vis();
	}
	// Event Listener on Button.onAction
	@FXML
	public void rstBtnClick(ActionEvent event) {
		// TODO Autogenerated
		initialize();
	}
}
